name: Deploy to EC2

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 65.0.89.238
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            if [ ! -s "$NVM_DIR/nvm.sh" ]; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            fi
            source $NVM_DIR/nvm.sh

            cd bms/
            git pull origin main
            pnpm install --frozen-lockfile
            pnpm run build
            pm2 reload http-server ws-server fd-server
